[project]
name = "Fractional-Real-Estate"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/workspace/Fractional-Real-Estate/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.fractional-ownership-v1]
path = "contracts/fractional-ownership-v1.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
